=== CeladonSS13/Shiptest/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"warra",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_caliban.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Caliban-class Modified Assault Vessel",
	"map_short_name": "Caliban",
	"description": "'Caliban' - это переделанное бронированное военное судно InteQ. Изначально данный корабль обладал килевым гибридным рельсотроном и внушительным количеством турелей точечной обороны. Ныне рельсотрон демонтирован, а батареи для него были заменены на хранилище или место было просто освобождено. После модификации корабль обладает маневренным десантным кораблем класса 'Tadpole', турелями, крепким корпусом и одним, но мощным двигателем. Сам корабль оснащен химической лабораторией, хирургией и достаточно развитым инженерным отделом, в то время как персонал делится на две части: судовой и боевой персонал. Судовой экипаж представляет собой санитара, занимающимся химией, двумя инженерами с их главой, а также арьергардом - офицером по связи и управлению кораблем в случае отсутствия капитана судна. Боевой персонал 'Caliban' мал для своего размера, однако он обладает невероятной гибкостью, командиром которого является почетный авангард в окружении элитной гвардии, обладающей экспериментальным оборудованием. Почетный авангард является символом 'братского' духа InteQ, работающий вместе со своими братьями и сестрами. Хоть тот и может стать лакомой целью пиратов или иных предприимчивых людей, но в данном случае безопасность его достигается броней корабля, его системами защиты, а также технологиями, которые оберегают отряд в бою.",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_caliban.dmm",
	"subshuttle": "Tadpole",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "BIQSV",
	"faction": "/datum/faction/inteq",
	"tags": [
		"Флагман",
		"Суб-шаттл",
		"Инженерный"
	],
	"namelists": [
		"MYTHOLOGICAL",
		"NATURAL_AGGRESSIVE",
		"INTEQ"
	],
	"job_slots": {
		"Honorable Vanguard": {
			"outfit": "/datum/outfit/job/inteq/cel/honorable",
			"officer": true,
			"slots": 1
		},
		"Rearguard": {
			"outfit": "/datum/outfit/job/inteq/cel/rearguard",
			"officer": true,
			"slots": 1
		},
		"Artificer Class II": {
			"outfit": "/datum/outfit/job/inteq/cel/ce",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/inteq/cel/engineer",
			"slots": 2
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/inteq/cel/paramedic",
			"slots": 2
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/inteq/cel/security",
			"slots": 2
		}

	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_forseti.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Forseti-class Patrol Cruiser",
	"map_short_name": "Forseti",
	"description": "Патрульно-полицейский Крейсер ”Forseti” оборудованный сабшаттлом ”Seer” является ответным ударом флота Федерации на участившиеся случае правонарушений среди гражданских суден. Данное судно, снабженное самым современным генератором энергии, ставит перед собой такую цель как: контроль гражданского оборота груза, миграции, контролем за соблюдением секториальных и федеративных прав и свобод, законодательств. Крейсер прекрасно оснащен нелетальными способами задержания и ведения боя.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_forseti.dmm",
	"subshuttle": "seer",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
		"Боевой",
		"Суб-шаттл",
		"РП Фокус"
	],
	"namelists": [
		"SOLFED",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 5
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 2
		},
		"Vertrags-Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/miner",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_inqrutsio.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Inqrutsio-Corvette Survey Ship",
	"map_short_name": "Inqrutsio",
	"description": "Корвет Солнечной Федерации предназначенный для сбора разведовательных данных, составления безопастных маршрутов, и в случае необходимости поддержки союзных сил. ",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_inqrutsio.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Специализированный"],
	"namelists": [
		"SOLFED"
	],
	"job_slots": {
		"Expeditionary Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 1
		},
		"Expeditionary Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 1

		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_tethra.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Tethra-class Response Vessel",
	"map_short_name": "Tethra",
	"description": "Корабль Солнечной Федерации класса Тетра относится к числу судов быстрого реагирования, зачастую использульзуемый в целях разведки и конвоирования заключенных. Несмотря на изначальные цели, судно снабжено необходимой экипировкой для участия в боевых столкновениях и рейдах. Несмотря на свои габариты, судно имеет превосходную маневренность и скорость. ",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_tethra.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 5,
	"starting_funds": 2000,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Боевой"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 2
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 1
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_crying_sun.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Crying Sun-class Light Frigate",
	"map_short_name": "Crying-Sun",
	"description": "Легкий фрегат производства Nanotrasen Spaceworks для перевозки массивных линейных боевых орудий при сохранении высокой маневренности. Оружейная установка на этом корабле была выведена из эксплуатации, как и многие другие подобные корабли, отправленные из пространства Каликскии. Класс «Crying Sun» — это судно, предназначенное для военно-морского и морского флота, на борту которого находится шаттл для абордажа, экскурсий и передовой разведки. После вывода из эксплуатации основного орудия двигатели были заменены на меньшую мощность, щедро поставлено инженерное оборудование. Так как этот корабль не заимел популярности, его производство было прекращено, а все оставшиеся корабли списаны. Но всё таки некоторые экземпляры смогли попасть на чёрный рынок, а далее и в руки любителей нелегальной деятельности.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_crying_sun.dmm",
	"subshuttle": "Nail",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Флагман",
		"Суб-шаттл"
	],
		"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Pirate Captain": {
			"outfit": "/datum/outfit/job/cel/pirate/captain/jupiter",
			"officer": true,
			"slots": 1
		},
		"Marine Sergeant": {
			"outfit": "/datum/outfit/job/cel/pirate/security/jupiter",
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/pirate/security",
			"slots": 3
		},
		"Pirate Engineer": {
			"outfit": "/datum/outfit/job/cel/pirate/engineer/jupiter",
			"slots": 1
		},
		"Pirate Doctor": {
			"outfit": "/datum/outfit/job/cel/pirate/medic",
			"slots": 1
		},
		"Pirate Crew": {
			"outfit": "/datum/outfit/job/cel/pirate/assistant/jupiter",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_paracelsus.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Paracelsus-class Medical Corvette",
	"map_short_name": "Paracelsus",
	"description": "Выполняя свою роль медицинского центра соларианского флота, корвет класса 'Paracelsus' специально спроектирован для помощи соларианским флотам в медицинских проблемах, а также для снабжения таких судов медикаментами. Писари, получающие медицинское образование, часто работают на этих суднах, чтобы стать тенью опытных медиков и пройти ординатуру. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Неизвестный и непонятный шип!",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_paracelsus.dmm",
	"enabled": false,
	"sensor_range": 4,
	"limit": 1,
	"prefix": "SFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["РП Фокус", "Медицинское"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Overseer": {
			"outfit": "/datum/outfit/job/solfed/hop",
			"officer": true,
			"slots": 1
		},
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/solfed/doctor",
			"slots": 3
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 1
		},
		"Field Engineer": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 2
		},
		"Scribe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 3
		},
		"Attentive Care Patient": {
			"outfit": "/datum/outfit/job/solfed/patient",
			"slots" : 3
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_cepheus.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Cepheus-class Patrool Corvette",
	"map_short_name": "Cepheus",
	"description": "Корвет класса 'Cepheus' является патрульным судном Солнечной Федерации, предназначенный для поддержания порядка на территории планет NE-24774. Дополнительно оснащен роботехнической лабораторией в целях развертывания дополнительных наземных сил и оказания универсальной поддержки. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Не балансился, с рандомной платой меха раундстартом!",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_cepheus.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
		"Боевой"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"WEAPONS",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 2
		},
		"Mechanized Armor Pilot": {
			"outfit": "/datum/outfit/job/cel/solfed/marine/pilot",
			"slots": 2
		},
		"Roboterkonstrukteur": {
			"outfit": "/datum/outfit/job/cel/solfed/scientist/roboticist",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_glimpse.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Glimpse-Architecture Survey Ship",
	"map_short_name": "Glimpse",
	"description": "Корабль архитектуры ПРОБЛЕСК, программы Солнечной Федерации исследований экзопланет и космических объектов на территориях фронтира. Корабль снабжен маневренным набором двигателей и аэродинамичным корпусом для широкого спектра атмосфер, что в купе с системами солнечных батарей помогает снизить нагрев судна при заходах на посадку самых разнообразных сред. Несмотря на поставленные задачи, судно весьма комфортабельно, так как длительные экспедиции имеют тенденцию негативно влиять на психику.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_glimpse.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Специализированный"],
	"namelists": [
		"SOLFED"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Marine Guard": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 2
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 1
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		},
		"N+S Contracted Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/nsminer",
			"slots": 2
		}
	}
}
