=== CeladonSS13/Shiptest/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"warra",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_krait.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Krait-class",
	"map_short_name": "Krait",
	"description": "Универсальный корабль класса 'Крайт', совмещает в себе две команды SnD и RnD. Команда SnD занимается поиском, захватом и уничтожением для второй команды занимающейся исследованиями. Корабль оснащен передовыми нанотехнологиями для более эффективной работы, обладает суб шаттлом для быстрого захвата и уничтожения объектов.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_krait.dmm",
	"subshuttle": "Jet_lancer",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "RSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Исследовательский" ],
	"namelists": ["CYBERSUN", "GORLEX"],
	"job_slots": {
		"Search and Destroy Team Leader": {
			"outfit": "/datum/outfit/job/syndicate/cel/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Search and Destroy team member": {
			"outfit": "/datum/outfit/job/syndicate/cel/security/gorlex",
			"slots": 3
		},
		"Research and Development Team Leader": {
			"outfit": "/datum/outfit/job/syndicate/cel/science/director",
			"officer": true,
			"slots": 1
		},
		"Research and Development team member": {
			"outfit": "/datum/outfit/job/roboticist",
			"slots": 3
		},
		"GEC Engineering": {
			"outfit": "/datum/outfit/job/syndicate/cel/engineer/gec",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_fist_of_freedom.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Fist of Freedom-class Administrative Battleship",
	"map_short_name": "Fist-of-Freedom",
	"description": "Платформа “Длань” - это современная универсальная платформа для создания кораблей широкого спектра задач, от авианесущих крейсеров, до боевых, тяжеловооруженных артиллерийских линкоров. Данный корабль имеет компоновку `Кулак Свободы`. Это линкор, используемый для установления контроля военной администрации флота над малонаселенными системами, для поддержания порядка, борьбы с преступностью, пиратством и терроризмом. Этот корабль оснащён самым современным генератором энергии, имеет на борту хорошо вооруженное отделение морской пехоты, а также оборудованием для автономного существования без регулярных продовольственных и ресурсных поставок. Всё что нужно для наведения порядка в системе Адмиралу флота, который наделён особыми полномочиями командования всеми судами Солнечной Федерации.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_fist_of_freedom.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "ASFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Флагман", "Административный"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"WEAPONS",
		"NATURAL"
	],
	"job_slots": {
		"Field Officer": {
			"outfit": "/datum/outfit/job/cel/solfed/captain/admiral",
			"officer": true,
			"slots": 1
		},
		"Personalvorgesetzter": {
			"outfit": "/datum/outfit/job/cel/solfed/hop",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 6
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 2
		},
		"Gehilfe": {
			"outfit": "/datum/outfit/job/cel/solfed/assistant",
			"slots" : 3
		},
		"N+S Contracted Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/nsminer",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_luxembourg.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Luxembourg-class Delivery Vessel",
	"map_short_name": "Luxembourg",
	"description": "Судно двойного назначения: доставка и продажа. Судно класса 'Luxembourg' составляет значительную часть флота Donk! Co. на границе, где вечно-оппортунистская корпорация начала заполнять пробелы, оставшиеся после краха логистической сети Nanotrasen. Менеджеры Donk! Co. обладают большой степенью автономии, и поэтому в любом конкретном корабле 'Luxembourg' часто приходится вносить существенные изменения в торговый зал и бортовое кафе, чтобы лучше привлекать новых клиентов в нестабильном, но прибыльном регионе пространства.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_luxembourg.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"starting_funds": 6000,
	"prefix": "TSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Торговый", "РП Фокус"],
	"namelists": [
		"DONK",
		"MERCANTILE",
		"SPACE"
	],
	"job_slots": {
		"Manager": {
			"outfit": "/datum/outfit/job/syndicate/cel/quartermaster/donk",
			"slots": 1
		},
		"Customer Service Representative": {
			"outfit": "/datum/outfit/job/syndicate/cel/cargo_tech/donk",
			"slots": 5
		},
		"Food and Beverage Specialist": {
			"outfit": "/datum/outfit/job/syndicate/cel/bartender",
			"slots": 1
		},
		"GEC Contracted Engineer": {
			"outfit": "/datum/outfit/job/syndicate/cel/engineer/gec",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_lightning.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Lightning Medical Light-Cruiser",
	"map_short_name": "Lightning",
	"description": " 'Lightning',  Модернизированная и переоборудованная версия одного из первых разведывательных космических кораблей регулярных сил Солнечной Федерации во времена космической экспансии о чем говорит его обшивка из сплава плазмы и титана черного цвета . Корабль оснащен современным медицинским оборудованием для поддержки союзных кораблей, а так же гумманитарных миссий на просторах Фронтира, а так же двигатели позволяющие развивать огромную скорость оправдывающие его название",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_lightning.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 7,
	"starting_funds": 2000,
	"prefix": "MSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
	"Медицинское"
	],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Marine Guard": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Medical Scientist": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor/medical_scientist",
			"officer": true,
			"slots":1
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 2
		},
		"Field Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 2
		}
	}
}
