=== CeladonSS13/Shiptest/_maps/_mod_celadon/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Схема Конфигурации Корабля",
	"description": "Конфигурация корабля, используемая для определения новых классов кораблей.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Название Класса",
			"type": "string",
			"description": "Название класса корабля, отображаемое в игре. Суффикс «-class» должен быть в нижнем регистре."
		},
		"map_short_name": {
			"title": "Сокращённое Название Класса",
			"type": "string",
			"description": "Сокращённая версия названия класса корабля, используется, например, в манифесте, а также используется для просмотр карт при покупке корабля, ссылаясь на сайт https://map.celadon.pro. Пробелы и символы запрещены. Исключения:'-' и '_'",
			"maxLength": 20
		},
		"description": {
			"title": "Описание Класса",
			"type": "string",
			"description": "Описание класса корабля. В настоящее время отображается показывается для игроков перед покупкой корабля, а также для администраторов в инструментах управления шаттлом.",
			"minLength": 250
		},
		"map_path": {
			"title": "Путь к Файлу Карты",
			"type": "string",
			"description": "Путь к файлу карты данного класса корабля. Используйте прямые слэши (/) для директорий и включайте расширение .dmm. Файлы карт должны находиться в папке '_maps/_mod_celadon'.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"subshuttle": {
			"title": "Название Субшаттла",
			"type": "string",
			"description": "Название Субшаттла, что добавлен на карту материнского корабля. Используется для дополнительного вывода информации при покупке корабля, а также для ссылки на карту субшаттла на сайте корабля."
		},
		"enabled": {
			"title": "Доступность",
			"type": "boolean",
			"description": "Можно ли выбрать этот корабль игрокам. Админы всё равно смогут его заспавнить.",
			"default": false
		},
		"roundstart": {
			"title": "Случайный Выбор на Старте Раунда",
			"type": "boolean",
			"description": "Определяет, может ли этот корабль быть случайно выбран в качестве бесплатного стартового корабля.",
			"default": false
		},
		"limit": {
			"title": "Ограничение на Спавн Кораблей",
			"type": "integer",
			"description": "Максимальное количество кораблей этого класса, которое может быть заспавнено игроками за раунд.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"sensor_range": {
			"title": "Дальность Сенсоров",
			"type": "number",
			"description": "Определяет максимальную дальность сенсоров корабля."
		},
		"starting_funds": {
			"title": "Стартовые Средства Корабля",
			"type": "integer",
			"description": "Количество денег на банковском счёте корабля при старте.",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"space_spawn": {
			"title": "Спавн в Космосе",
			"type": "boolean",
			"description": "Определяет, появится ли корабль в космосе или на аванпосте.",
			"default": false
		},
		"prefix": {
			"title": "Префикс Корабля",
			"type": ["null", "string"],
			"description": "Префикс класса корабля, который добавляется к случайно сгенерированным именам при покупке.",
			"maxLength": 6
		},
		"faction": {
			"title": "Фракция Корабля",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"description": "Фракция по умолчанию."
		},
		"manufacturer": {
			"title": "Производитель Корабля",
			"type": ["null", "string"],
			"description": "Производитель класса корабля, в данный момент не используется, но будет использоваться в автоматических вики-шаблонах."
		},
		"tags": {
			"title": "Теги Корабля",
			"type": "array",
			"description": "Список тегов, описывающих особенности корабля, которые можно использовать для поиска."
		},
		"namelists": {
			"title": "Списки Имен",
			"type": "array",
			"description": "Список имен, из которого этот класс корабля будет выбирать случайное имя при покупке. Все варианты можно найти в файле ship_names.json.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"warra",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLFED",
					"CMM-GOLD",
					"CMM-BARD",
					"PGF"
				]
			}
		},
		"job_slots": {
			"title": "Рабочие Места",
			"description": "Список рабочих мест, доступных на этом корабле. Первый слот всегда отводится под 'капитана', которым становится покупатель.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "Предустановленная должность, должна совпадать с названием работы в коде (названия работ можно найти в соответствующих файлах)."
					},
					{
						"type": "object",
						"description": "Пользовательская должность, может быть любым названием, но требует указания униформы и количества слотов.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "Название униформы (outfit), которая будет использоваться в этом слоте. Должно быть точным, иначе вызовет ошибку.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Определяет, является ли должность офицерской. Офицерские должности получают шеврон в манифесте, а количество их слотов нельзя изменять в игре.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "Количество доступных мест в этом слоте при старте раунда. Экипаж может изменить его в игре, но не более чем вдвое.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"spawn_time_coeff": {
			"title": "Коэффициент Времени Спавна",
			"type": "number",
			"description": "Множитель, используемый для расчёта минимального времени игры в живом состоянии, необходимого для спавна этого корабля.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Коэффициент Времени Офицера",
			"type": "number",
			"description": "Множитель, определяющий минимальное время игры в живом состоянии, необходимое для спавна в офицерской должности на этом корабле.",
			"minimum": 0,
			"default": 1
		}
	},
		"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_firetail.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Firetail-class Expeditionary Frigate",
	"map_short_name": "Firetail",
	"description": "Фрегат класса 'Firetail' с субшаттлом класса 'Vespa' на борту – экспедиционно-патрульный корабль флота Солнечной Федерации, переоборудованный с поддержкой дочерней компании  'NanoTrasen™' - 'North Star™', что отвечала за оснащение корабля шахтёрским оборудованием и предоставлением дополнительных кадров, в лице шахтёров на контрактной основе. Сам корабль отличается наличием отделения телекоммуникаций и сбалансированным оборудованием, делая корабль полностью автономным и гибким, что идеально подходит для долгосрочных боевых миссий.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_firetail.dmm",
	"subshuttle": "Vespa",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": [
		"Боевой",
		"Суб-шаттл"
	],
	"namelists": [
		"SOLFED",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Expeditionary Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Feldwebel": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Expeditionary Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 3
		},
		"Expeditionary Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 1
		},
		"Expeditionary Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		},
		"N+S Contracted Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/nsminer",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_valor.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Valor-Class Field Care Cruiser",
	"map_short_name": "Valor",
	"description": "'Valor' — специализированное медицинское судно флота Inteq, подходящее как для лечения раненых в боях членов Inteq, так и для платного лечения посторонних. Для этой цели он оснащен высококлассным медицинским оборудованием и небольшим шаттлом для перевозки пациентов.",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_valor.dmm",
	"subshuttle": "Haste",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "SPIQSV",
	"faction": "/datum/faction/inteq",
	"tags": ["Медицинское", "Суб-шаттл"],
	"namelists": [
		"MYTHOLOGICAL",
		"NATURAL",
		"INTEQ"
	],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/inteq/celadon/captain",
			"officer": true,
			"slots": 1
		},
		"Honorable Corpsman": {
			"outfit": "/datum/outfit/job/inteq/celadon/cmo",
			"officer": true,
			"slots": 1
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/inteq/celadon/paramedic",
			"slots": 3
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/inteq/celadon/security",
			"slots": 2
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/inteq/celadon/assistant",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_tortuga.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Tortuga-class Converted Cargo Freighter",
	"map_short_name": "Tortuga",
	"description": "Изначально 'Tortuga' была грузовым транспортным судном, но теперь является импровизированным боевым кораблем, используемым флотом пограничников. Гражданские транспортные средства оснащены оборудованием для перевозки челноков, а обломки астероидов прикреплены к внешней части корпуса в качестве дешевой импровизированной брони и укрытия. 'Tortuga' выполняет двойную функцию - это разведывательный элемент и судно, способное создавать передовые базы в пределах сектора. В то время как шаттл класса 'Brawler', который перевозит 'Tortuga', обеспечивает удивительную скорость и дальность полета для своих абордажных групп, сама 'Tortuga' неповоротлива и почти беспомощна без своего шаттла. В щитспавне по причине: Пираты - судно оффов, уродский внешний вид, но баланс вооружения нормальный. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Сильный пирато шип для ивентов!",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_tortuga.dmm",
	"subshuttle": "Brawler",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Боевой",
		"Суб-шаттл"
	],
	"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/captain",
			"officer": true,
			"slots": 1
		},
		"Deck Boss": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/hos",
			"officer": true,
			"slots": 1
		},
		"Surgeon": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/doctor",
			"slots": 1
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/engineer",
			"slots": 1
		},
		"Boarder": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/security",
			"slots": 2
		},
		"Rookie": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/assistant",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_inkwell.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Inkwell-class Supply Freighter",
	"map_short_name": "Inkwell",
	"description": "Одно из немногих суден, спроектированных Солом и используемых вне официального контекста сторонами, не входящими в Конфедерацию, Судно класса 'Inkwell' - грузовое судно, уважаемое за свою инженерную мысль и любимое за роскошные помещения для экипажа. 'Inkwell' можно встретить во многих контекстах, но, пожалуй, больше всего среди Вервальтунгскомпаниен, где они играют важную роль в решении логистических проблем любой надлежащей военной администрации. Кроме того, их часто заказывают и продают несоларианцам для использования в межзвездных перевозках. Об использовании 'Inkwell' для перевозки незаконных или неотслеживаемых грузов известно любому опытному (или даже полуопытному) портовому начальству; '...такие прискорбные действия со стороны исключительного меньшинства - лишь часть реалий межзвездных перевозок.' - говорится в официальном ответе.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_inkwell.dmm",
	"subshuttle": "Feather",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Специализированный", "Суб-шаттл"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Logistics Deck Officer": {
			"outfit": "/datum/outfit/job/solfed/quartermaster",
			"officer": true,
			"slots": 1
		},
		"Sonnensöldner": {
			"outfit": "/datum/outfit/job/solfed/marine",
			"slots": 3
		},
		"Field Marinemechaniker": {
			"outfit": "/datum/outfit/job/solfed/engineer",
			"slots": 2
		},
		"Vertrags-Miner": {
			"outfit": "/datum/outfit/job/solfed/miner",
			"slots": 3
		},
		"Gehilfe": {
			"outfit": "/datum/outfit/job/solfed/assistant",
			"slots" : 6
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_tomahawk.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Tomahawk-class Scout Vessel",
	"map_short_name": "Tomahawk",
	"description": "Корабль Солнечной Федерации класса Томагавк служит для фронтовой разведки с боем, cо временем начала космических экспансий 23 века о чем может подсказывать его обшивка. Данный корабль обладает хорошей скоростью, не смотря на свои габариты. На судне предусмотрены рабочие места для двух медиков, трёх полевых инженеров и одного корабельного.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_tomahawk.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 2000,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Боевой"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Feldwebel": {
			"outfit": "/datum/outfit/job/cel/solfed/sergeant",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 3
		},
		"Meeresarzt": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		},
		"N+S Contracted Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/nsminer",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_saber.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Saber-class Patrool Corvette",
	"map_short_name": "Saber",
	"description": "Корабль класса `Сабля` это производящийся на территории NE-24761 патрульный корабль, используемый Анти-Террористическим корпусом Солнечной Федерации-52, для поддержания порядка, борьбы с преступностью и терроризмом. Конкретно данное судно принадлежит `Бригаде Элизиума`, добровольческом полку Солнечной Федерации состоящим из граждан Элизиума. Несмотря на то что они имеют собственную униформу, они подчиняются Солнечной Федерации.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_saber.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Боевое", "РП Фокус"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"WEAPONS",
		"NATURAL"
	],
	"job_slots": {
		"Musharif": {
			"outfit": "/datum/outfit/job/solfed/captain/elysium",
			"officer": true,
			"slots": 1
		},
		"Mulazim": {
			"outfit": "/datum/outfit/job/solfed/sergeant/elysium",
			"officer": true,
			"slots": 1
		},
		"Haris": {
			"outfit": "/datum/outfit/job/solfed/marine/elysium",
			"slots": 4
		},
		"Shafi": {
			"outfit": "/datum/outfit/job/solfed/doctor/elysium",
			"slots": 1
		},
		"Khabeer Fanni": {
			"outfit": "/datum/outfit/job/solfed/engineer/elysium",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_chronicle.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Chronicle-class Research and Development Frigate",
	"map_short_name": "Chronicle",
	"description": "Научно-исследовательское судно класса 'Chronicle' — высокотехнологичный фрегат Солнечной Федерации, оснащённый всем необходимым для эффективных исследований в различных областях науки. Судно оборудовано дорогостоящим ядром ИИ и хранилищем для него, рассчитано на длительные экспедиции в удалённые сектора космоса, укомплектовано исследовательской группой из высококвалифицированных сотрудников под руководством научного руководителя и коменданта, а также всем, что необходимо для продуктивного старта экспедиций. Эти качества делают 'Chronicle' одним из лучших научных судов, когда‑либо разработанных Солнечной Федерацией.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_chronicle.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Исследовательский"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"job_slots": {
		"Kommandant": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Scientific Overseer": {
			"outfit": "/datum/outfit/job/cel/solfed/doctor/medical_scientist/overseer",
			"officer": true,
			"slots": 1
		},
		"Marine": {
			"outfit": "/datum/outfit/job/cel/solfed/marine",
			"slots": 1
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		},
		"N+S Contracted Miner": {
			"outfit": "/datum/outfit/job/cel/solfed/nsminer",
			"slots": 2
		},
		"Field Science Assistant": {
			"outfit": "/datum/outfit/job/cel/solfed/scientist",
			"slots" : 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_anomaly.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Anomaly-class Experimental Project",
	"map_short_name": "Anomaly",
	"description": "Проект 'Anomaly' - экспериментальная разработка Солнечной Федерации, которая содержит в себе попытки использовать аномалии для производства ресурсов, таких как энергия и топливо. При строительстве этого корабля трубы и провода интегрировали в стены, из-за чего его перестройка может быть проблематичной.",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_anomaly.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 6,
	"starting_funds": 0,
	"prefix": "SPSFSV",
	"faction": "/datum/faction/solgov",
	"tags": ["Специализированный"],
	"namelists": [
		"SOLFED",
		"SPACE",
		"NATURAL"
	],
	"job_slots": {
		"Scientific Overseer": {
			"outfit": "/datum/outfit/job/cel/solfed/captain",
			"officer": true,
			"slots": 1
		},
		"Logistikbeauftragter": {
			"outfit": "/datum/outfit/job/cel/solfed/quartermaster",
			"officer": true,
			"slots": 1
		},
		"Wissenschaftler": {
			"outfit": "/datum/outfit/job/cel/solfed/scientist",
			"slots": 2
		},
		"Marinemechaniker": {
			"outfit": "/datum/outfit/job/cel/solfed/engineer",
			"slots": 1
		}
	}
}
