=== CeladonSS13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"MAKOSSO-WARRA",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_gorlex_hyena.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Hyena-class Wrecking Tug",
	"map_short_name": "Hyena",
	"description": "«Hyena» обычный спасательный буксир, который часто используется «Мародерами Горлекса» для «спасательных» миссий на заброшенные станции эпохи Второй Галактической войны (а, иногда и на аванпосты и судна). 'Hyena' имеет довольно компактную планировку со специальным безопасным складским помещением и довольно большим грузовым отсеком для своего размера, а также комплектом высококачественных костюмов и шахтёрского оборудования. Низкая стоимость Hyena и высокий спрос в ее нише сделали ее очень распространенным явлением в дальних секторах космоса в годы, последовавшие за войной. и несмотря на ограниченное финансирование, почти все отколовшиеся от фракции Мародёров Горлекса продолжают приобретать такие типы суден ещё больше.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_gorlex_hyena.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"prefix": "DSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Шахтерский"],
	"namelists": [
		"GORLEX",
		"NATURAL_AGGRESSIVE",
		"BEASTS",
		"WEAPONS",
		"ACLF"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/syndicate/cel/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Foreman": {
			"outfit": "/datum/outfit/job/syndicate/cel/ce/ngr",
			"officer": true,
			"slots": 1
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/syndicate/cel/engineer/gorlex",
			"slots": 1
		},
		"Wrecker": {
			"outfit": "/datum/outfit/job/syndicate/cel/miner/gorlex",
			"slots": 2
		},
		"Junior Agent": {
			"outfit": "/datum/outfit/job/syndicate/cel/assistant/gorlex",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_skipjacker.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Skipjacker-class Scavenger",
	"map_short_name": "Skipjacker",
	"description": "Скипджеккер — небольшой, но юркий корабль, чей экипаж состоит в основном из воксов-изгоев, вынужденных выживать в роли мусорщиков и разбойников. Из-за устаревшей конструкции запасы кислорода на борту сильно ограничены, однако при умеренном расходе их хватит на достаточно долгое время.(Напомню! В течение первых 10 минут после спавна корабля, вы можете заменить первую букву своего исходного префикса на «R», чтобы стать пиратом. Перед этим обязательно сообщите администрации!)",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_skipjacker.dmm",
	"enabled": true,
	"limit": 1,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Combat",
		"RP Focus",
		"Hydroponics",
		"Salvage",
		"Generalist"
	],
	"namelists": [
		"MERCANTILE",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Quill": {
			"outfit": "/datum/outfit/job/independent/captain",
			"officer": true,
			"slots": 1
		},
		"Scavengers": {
			"outfit": "/datum/outfit/job/independent/engineer/salvage",
			"slots": 2
		},
		"Technician": {
			"outfit": "/datum/outfit/job/independent/engineer",
			"slots": 1
		},
		"Doctor": {
			"outfit": "/datum/outfit/job/independent/doctor",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_elegia.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Elegia-class War Galeon",
	"map_short_name": "Elegia",
	"description": "Исследовательский корвет под названием Элегия предназначен для исследовательских задач, ведь он может находиться длительное время на самообеспечении. Основной целью является исследование планет и фауны. Для этого он оснащен шахтёрским инвентарём, боевым оружием и средствами стабилизации полевых оперативников, а также специальным медицинским боргом Синдиката.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_elegia.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 6,
	"prefix": "BSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Боевой"],
	"namelists": [
		"GORLEX"],
	"job_slots": {
		"Hardliner's Captain": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Hardliner's Doctor": {
			"outfit": "/datum/outfit/job/cel/syndicate/paramedic/gorlex",
			"slots": 1
		},
		"Hardliner's mechanic": {
			"outfit": "/datum/outfit/job/cel/syndicate/engineer/gorlex",
			"slots": 1

		},
		"Hardliner's Operative": {
			"outfit": "/datum/outfit/job/cel/syndicate/security/gorlex",
			"slots": 3
		},
		"Hardliner's miner": {
			"outfit": "/datum/outfit/job/cel/syndicate/miner/gorlex",
			"slots": 2
		},
		"Junior Agent": {
			"outfit": "/datum/outfit/job/cel/syndicate/assistant/gorlex",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/elysium_atlas.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Atlas-class Drug Production Vessel",
	"map_short_name": "Atlas",
	"description": "Корветы класса «Atlas» когда-то использовались Республикой Элизиум, но несколько десятилетий назад были законсервированы. Сегодня корабли используются Сепаратистами Элизиума как корабли снабжения и полевого производства столь необходимых сепаратистам ветвей амброзии. Многие из них выгорели изнутри в плазменных пожарах из-за фатального несоблюдения техники безопасности при транспортировке газообразной плазмы. На них также находятся субшаттлы класса 'Felon', которые теперь используются для быстрой переброски (обычно контрабандных) припасов.",
	"map_path": "_maps/_mod_celadon/shuttles/elysium/elysium_atlas.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"prefix": "EUSM",
	"faction": "/datum/faction/elysium",
	"tags": [
		"RP Focus",
		"Botany",
		"Cargo",
		"Subshuttle"
	],
	"namelists": [
		"WEAPONS",
		"BEASTS"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/elysium/captain",
			"officer": true,
			"slots": 1
		},

		"Mukatell": {
			"outfit": "/datum/outfit/job/elysium/security",
			"slots" : 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/elysium/assistant",
			"slots": 5
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_cybersun_cirrus.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Cirrus-class Medical Carrack",
	"map_short_name": "Cirrus-class",
	"description": "Cirrus-class — это проект Cybersun, созданный для  предоставления услуг Trauma Team в дали от основных объектов Cybersun. Он полностью оборудован для автономной работы судна, а также имеет пристыкованный к нему шаттл класса Gauze, для высадки Trauma Team к пострадавшим.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_cybersun_cirrus.dmm",
	"starting_funds": 1000,
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "MSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Медицинское"],
	"namelists": [
		"CYBERSUN",
		"SPACE",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/syndicate/captain/cybersun",
			"officer": true,
			"slots": 1
		},
		"Medical Director": {
			"outfit": "/datum/outfit/job/syndicate/cmo",
			"officer": true,
			"slots": 1
		},
		"Cybersun Ambassador": {
			"outfit": "/datum/outfit/job/syndicate/head_of_personnel/cybersun",
			"officer": true,
			"slots": 1
		},
		"Cybersun Technician": {
			"outfit": "/datum/outfit/job/syndicate/engineer/cybersun",
			"slots": 1
		},
		"Cybersun Medical Specialist": {
			"outfit": "/datum/outfit/job/syndicate/doctor/cybersun",
			"slots": 2
		},
		"Trauma Team Technician": {
			"outfit": "/datum/outfit/job/syndicate/paramedic/cybersun",
			"slots": 2
		},
		"Ship's Aide": {
			"outfit": "/datum/outfit/job/syndicate/assistant/cybersun",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_jupiter.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Jupiter-class Stormrider",
	"map_short_name": "Jupiter",
	"description": "Штурмовое судно класса 'Jupiter' (Noderider) - это специализированное судно, созданное Советом Кремниевого Возвышения, который обычно используется для длительных миссий без сторонней поддержки. Данное судно оснащено ядром ИИ и уникальной системой зарядки от электроштормов. Известно, что некоторые экземпляры попадали в руки пиратов, которые использовали судно, чтобы устраивать засады на ничего не подозревающих торговцев. В связи с тем, что данное судно требует высокой квалификации и обученного экипажа, оно не сыскало популярности в широких кругах, но заинтересовало представителей военных структур в отставке. Организованность данных бойцов вкупе с оснащенностью и уникальной особенностью судна, делают 'Jupiter' очень опасным представителем среди пиратских суден.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_jupiter.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 7,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"ИИ",
		"Специализированный",
		"Боевой"
	],
	"namelists": [
		"INSTALLATION",
		"PIRATES"
	],
	"job_slots": {
		"Command Node": {
			"outfit": "/datum/outfit/job/pirate/captain/jupiter",
			"officer": true,
			"slots": 1
		},
		"Assault Node": {
			"outfit": "/datum/outfit/job/pirate/security/jupiter",
			"slots": 5
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_rondo.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Rondo-class Renegate Assault Vessel",
	"map_short_name": "Rondo",
	"description": "'Rondo' - Cудно ранее используемое синдикатом как разведывательное, изначально снабжалось системой оптического камуфляжа. Однако из-за несовершенства технологии, любое повреждение экранирования приводило к полному отключению систем, в связи с чем судну требовался длительный ремонт. Ко всему прочему, использование технологии оптического камуфляжа, а тем более его ремонт требовали высокую степень квалификации экипажа, в результате чего система камуфляжа была снята, а сами суда из-за своей малой эффективности отправлены на утилизацию в верфи конструкторского бюро. От полного уничтожения данные суда были спасены во время рейда группировкой Рамзи, благодаря чему некоторые экземпляры попали на черный рынок, а оставшиеся до сих пор находятся во владении некоторых боевых формирований, в том числе и Ренегатов.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_rondo.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 6,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Боевой",
		"Выживание"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Battle Master": {
			"outfit": "/datum/outfit/job/cel/pirate/ramzi/captain",
			"officer": true,
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/cel/pirate/ramzi/trooper",
			"slots": 4
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_bubble.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Bubble-class Colonial Ship",
	"map_short_name": "Bubble",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_bubble.dmm",
	"description": "В то время как самые известные судна-колонии были громадными, высокоразвитыми кораблями, предназначенными для переправки сотен, а то и тысяч поселенцев в далекие миры и создания городов за считанные месяцы - Каликсианский Лунный свет, Кандор, Первый поезд в Форт-Сол, - судно класса 'Bubble' предназначен для тех, кто хочет основать небольшое ранчо или деревню на просторах космоса. Bubble очень компактны, но оснащены всем необходимым для создания колонии - обширным научно-исследовательским оборудованием, надежной добывающей техникой и карго подом для быстрой продажи культуры/руды и других продуктов от производства колонии. Несмотря на то, что исторически корабли класса 'Bubble' использовались Соларианской Федерацией для создания колоний, их собственная версия недавно была снята с эксплуатации.",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": ["Исследовательское"],
	"namelists": [
		"GENERAL",
		"SPACE"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/independent/captain",
			"slots": 1
		},
		"Scientist": {
			"outfit": "/datum/outfit/job/independent/scientist",
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/independent/engineer",
			"slots": 1
		},
		"Miner": {
			"outfit": "/datum/outfit/job/independent/miner",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/independent/assistant",
			"slots": 3
		}
	}
}
