=== CeladonSS13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"MAKOSSO-WARRA",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_colossus.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Colossus-class Armored Frigate",
	"map_short_name": "Colossus",
	"description": "Как и большинство суден InteQ, 'Colossus' является профессионально военизированным грузовым судном и рассчитан на длительную автономную работу, служа интересам IRMG и предоставляя жизненно важные услуги наемников везде, где они необходимы. Ключевыми особенностями судна являются надежный и хорошо укомплектованный арсенал и просторные помещения для экипажа, а также вместительный грузовой отсек, который экипаж часто переоборудует в дополнительное место для отдыха или тренировок.",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_colossus.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BIQSV",
	"faction": "/datum/faction/inteq",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"MYTHOLOGICAL",
		"BEASTS",
		"NATURAL_AGGRESSIVE",
		"INTEQ"
	],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/inteq/cel/captain/honorable",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/inteq/cel/warden",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/inteq/cel/engineer",
			"slots": 1
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/inteq/cel/cmo",
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/inteq/cel/security",
			"slots": 3
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/inteq/cel/assistant",
			"slots": 5
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_pangolier.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Pangolier-class Cruiser",
	"map_short_name": "Pangolier",
	"description": "Судно класса «Pangolier» является результатом совместного сотрудничества Cybersun и Gorlex Marauders. Благодаря их совместному труду в краткие сроки некогда вышедшее из эксплуатации административное судно было отреставрировано и переоборудовано под длительные экспедиции, а также снабжено научным отделом. На судне находятся ведущие специалисты своих областей под командованием предоставленного Cybersun Капитана, в то же время для их защиты на судне расквартирована наемная группа Gorlex Marauders.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_pangolier.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "RSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Исследовательский"],
	"namelists": ["CYBERSUN", "GORLEX"],
	"job_slots": {
		"Commander": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain/cybersun",
			"officer": true,
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/cel/syndicate/security/gorlex",
			"slots": 2
		},
		"Scientist": {
			"outfit": "/datum/outfit/job/cel/syndicate/science/cybersun",
			"slots": 2
		},
		"Paramedic": {
			"outfit": "/datum/outfit/job/cel/syndicate/doctor/cybersun",
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/cel/syndicate/engineer/cybersun",
			"slots": 2
		},
		"Junior Agent": {
			"outfit": "/datum/outfit/job/cel/syndicate/assistant",
			"slots": 2
		}

	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_gorlex_sunset.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Sunset-class Warship",
	"map_short_name": "Sunset",
	"description": " «Sunset» — созданный корабль на основе уроков межкорпоративных войн для замены устаревших типов кораблей класса «Komodo». Он представляет собой новейший средний боевой корабль, сочетающий в себе компактность, надёжность и скорость, идеально подходящий для быстрых и маневренных операций в любой ситуации.  На борту носит группу из 5 элитных бойцов, каждый из которых является мастером в своём деле.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_gorlex_sunset.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 4,
	"faction": "/datum/faction/syndicate",
	"prefix": "BSSV",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"GORLEX",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Squad Leader": {
			"outfit": "/datum/outfit/job/syndicate/cel/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Combat Medic": {
			"outfit": "/datum/outfit/job/syndicate/cel/doctor/gorlex",
			"slots": 1
		},
		"Combat Engineer": {
			"outfit": "/datum/outfit/job/syndicate/cel/engineer/gorlex",
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/syndicate/cel/security/gorlex",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_escapepod.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Escape Pod X-03",
	"map_short_name": "EscapePod",
	"description": "Ваше основное судно было уничтожено, теперь вам нужно выжить.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_escapepod.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 2,
	"space_spawn": true,
	"prefix": "ЕSV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Выживание"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/independent/captain/western",
			"officer": true,
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/doctor",
			"slots": 1
		},
		"Ship's Engineer": {
			"outfit": "/datum/outfit/job/cel/independent/engineer",
			"slots": 1
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/cel/independent/miner/hazard",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/cel/independent/assistant",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/solfed_lightning_bolt.json
{
	"$schema": "https://raw.githubusercontent.com/shiptest-ss13/Shiptest/master/_maps/ship_config_schema.json",
	"map_name": "Bolt-class Scout Vessel",
	"faction": "/datum/faction/solgov",
	"prefix": "SFSV",
	"namelists": [
		"SOLGOV",
		"SPACE",
		"BRITISH_NAVY",
		"NATURAL"
	],
	"map_short_name": "Tomahawk-class",
	"map_path": "_maps/_mod_celadon/shuttles/solfed/solfed_lightning_bolt.dmm",
	"starting_funds": 0,
	"description": "Корабль Солнечной Федерации класса Bolt служит для фронтовой разведки с боем.",
	"tags": ["Разведка", "Бой", "Шахтёрство"],
	"limit": 1,
	"job_slots": {
		"Juggernaut": {
			"outfit": "/datum/outfit/job/solgov/bolt/captain",
			"officer": true,
			"slots": 1
		},
		"Scout": {
			"outfit": "/datum/outfit/job/solgov/bolt/bureaucrat",
			"officer": true,
			"slots": 1
		},
		"Assault": {
			"outfit": "/datum/outfit/job/solgov/bolt/security",
			"slots": 1
		},
		"Stormtrooper": {
			"outfit": "/datum/outfit/job/solgov/bolt/security",
			"slots": 2
		},
		"Paramedic": {
			"outfit": "/datum/outfit/job/solgov/bolt/medic",
			"slots": 2
		},
		"Demolitionist": {
			"outfit": "/datum/outfit/job/solgov/bolt/engineer",
			"slots": 1
		}
	},
	"enabled": false
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/elysium_aldaama.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Aldaama-class Experimental Project",
	"map_short_name": "Aldaama",
	"description": "Изначально 'Алдаама' работал на двигателе Сингулярности, но после ее побега, никто даже не заикался снова ввести ее в эксплуатацию. Вместо этого сделали более безопасный двигатель Тесла. На данный момент у Республики Элизиума всего два таких корабля. Один стоит в музее 'Алехар'(каменистая планета 'Лер'), а второй активно используется сепаратистами Элизиума как корабль снабжения и оперативной телекоммуникационной базой.",
	"map_path": "_maps/_mod_celadon/shuttles/elysium/elysium_aldaama.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Специализированный",
		"Боевое",
		"РП Фокус"
	],
	"namelists": [
		"SPACE",
		"WEAPONS",
		"ENGINEERING"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/elysium/assistant",
			"slots": 3
		},
		"Mukatell": {
			"outfit": "/datum/outfit/job/elysium/security",
			"slots" : 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_caravan.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Caravan-class Modular ship",
	"map_short_name": "Caravan",
	"description": "Caravan - относительно новое грузовое судно, созданное на основе модульной системы капсул, которая позволяет судну выполнять различные функции, помимо простой транспортировки. Эти капсулы сконструированы на основе быстросъемного механизма, который позволяет главному корпусу прыгать в голубое пространство, отсоединять капсулы и загружать новый набор пустых капсул типа Caravan за считанные минуты. Хотя в теории это впечатляет, отсутствие пустых совместимых грузовых капсул в пространстве Фронтира делает систему быстрого отсоединения бесполезной. Кроме того, модульная система крепления подвержена износу, что требует более частого и дорогостоящего обслуживания, чем у других грузовых суден. Несмотря на эти недостатки, 'Caravan' заслужил репутацию универсальной платформы для самых разных миссий. Основной корпус оснащен надежной силовой установкой и достойными местами для экипажа, а большинство суден на Фронтире оснащены капсулами, предназначенными для добычи полезных ископаемых и проведения исследований. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Наличие ТЭГа убивает сервер!",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_caravan.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Исследовательский"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"MYTHOLOGICAL",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/independent/captain/western",
			"officer": true,
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/independent/doctor",
			"slots": 1
		},
		"Engine Technician": {
			"outfit": "/datum/outfit/job/independent/atmos",
			"slots": 1
		},
		"Asteroid Miner": {
			"outfit": "/datum/outfit/job/independent/miner",
			"slots": 1
		},
		"Fauna Researcher": {
			"outfit": "/datum/outfit/job/independent/scientist",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/independent/assistant",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_santiana.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Santiana-class Contrabandist",
	"map_short_name": "Santiana",
	"description": "Боевая шхуна контрабандистов - пиратов. Собранная на скорую руку за самую низкую плату на рынке - эта модель замечается на окраинах космоса в качестве манёвренной и быстрой посудины для доставки и получения контрабанды от разных поставщиков. Благодаря некоторым махинациям, данное судно обзавелось каргопадом и маяком черного рынка, блягодаря чему они стали незаменимыми помощниками для других любителей незаконной деятельсности у которых нет доступа на общественный рынок. Также он популярен у чёрных трансплантологов благодаря достаточно хорошо укопмлектованому мед-отсеку (по меркам контрабандистов).",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_santiana.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Специализированный",
		"Торговый",
		"РП Фокус"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Kapitan": {
			"outfit": "/datum/outfit/job/pirate/captain",
			"officer": true,
			"slots": 1
		},
		"Abordajnik": {
			"outfit": "/datum/outfit/job/pirate/security",
			"slots": 1
		},
		"Povar": {
			"outfit": "/datum/outfit/job/independent/cook",
			"slots": 1
		},
		"Motorist": {
			"outfit": "/datum/outfit/job/pirate/engineer",
			"slots": 1
		},
		"Korabelniy vrach": {
			"outfit": "/datum/outfit/job/pirate/medic",
			"slots": 1
		},
		"Yunga": {
			"outfit": "/datum/outfit/job/pirate/assistant",
			"slots": 1
		}
	}
}
