=== CeladonSS13/Shiptest/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"MAKOSSO-WARRA",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/syndicate_mite.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Mite-class Mining Shuttle",
	"map_short_name": "Mite",
	"description": "Шаттл класса «Mite» был разработан Gorlex Marauder в результате отчаянной попытки противостоять растущей экспансии TPG в сфере добычи материалов. Однако затея не увенчалась успехом, и переоборудование «Jet Lancer» было прекращено. В настоящий момент сохранившиеся экземпляры пользуются небольшой популярностью у разведывательных групп, поскольку для работы и обслуживания судна требуется не более двух человек.",
	"map_path": "_maps/_mod_celadon/shuttles/syndicate/syndicate_mite.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "DSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Шахтерский"],
	"namelists": ["GORLEX"],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"Junior Agent": {
			"outfit": "/datum/outfit/job/cel/syndicate/assistant/gorlex",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/elysium_homafasher.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Homafasher-class Mining Corvette",
	"map_short_name": "Homafasher",
	"description": "По меркам шуры Аль-Фада, 'Хомафашер' — старый, но надёжный и проверенный временем корабль. Его история начинается на верфях Республики Элизиум, это корвет массового производства, с достаточно дешевым ценником для его габаритов. Этот звездолет используется буквально везде: начиная от гос. учреждений, заканчивая приватными компаниями. И, как не удивительно, сепаратистами. Вариантов судна очень много, но в случае с Хомафашер - это одна из самых дешевых версий, предназначенная для горнопромышленных целей и оснащенная базовым медицинским отсеком.",
	"map_path": "_maps/_mod_celadon/shuttles/elysium/elysium_homafasher.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Боевое",
		"Шахтерский",
		"РП Фокус"
	],
	"namelists": [
		"SPACE",
		"WEAPONS"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Mukatell": {
			"outfit": "/datum/outfit/job/elysium/security",
			"slots": 2
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/elysium/assistant",
			"slots" : 3
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_iron_maiden.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Iron-class Assault Boat Mk.II",
	"map_short_name": "Inteq-Iron-Maiden",
	"description": "Тяжелое десантное судно класса 'Iron' или известного как Утюг, модификация Марк 2, представляет собой последний штрих в области десантных операций. Отсеки судна были переработаны с учетом опыта предыдущих боевых действий, что повысило безопасность при штурме судна. Производимый корпорацией InteQ, это судно широко используется в качестве десантного судна на кораблях-носителях, но также способен выполнять самостоятельные полеты в пределах солнечной системы. Разработанный в начале конфликта с другими корпорациями, он представляет собой более доступную альтернативу сложным и дорогостоящим судам. Известный своим прямоугольным корпусом и мощной броней, Марк 2 обеспечивает надежную защиту для десантников в самых опасных условиях. Несмотря на то, что это судно прослужило уже не одно десятилетие, его популярность не угасает благодаря простоте и высокой степени надежности.",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_iron_maiden.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"prefix": "LIQSV",
	"faction": "/datum/faction/inteq",
	"tags": ["Боевой"],
	"namelists": [
		"MYTHOLOGICAL",
		"BEASTS",
		"NATURAL_AGGRESSIVE",
		"INTEQ"
		],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/inteq/celadon/captain",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/inteq/celadon/enforcer",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/inteq/celadon/engineer",
			"slots": 1
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/inteq/celadon/paramedic",
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/inteq/celadon/security",
			"slots": 5
		}
		}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_hammerhead.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Hammerhead-Heavy Cruiser",
	"map_short_name": "Hammerhead",
	"description": "Тяжёлый крейсер InteQ класса `Hammerhead` - бывшее исследовательское судно Нанотрейзен, выкупленное и перестроенное для использования в секторах без поддержки основных сил. Судно предназначено для большой и сплочённой команды из четырёх и более человек. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Наличие ТЭГа убивает сервер!",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_hammerhead.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BIQSV",
	"faction": "/datum/faction/inteq",
	"tags": [
		"Боевой",
		"Инженерный"
	],
	"namelists": [
		"INTEQ"
		],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/inteq/celadon/captain",
			"officer": true,
			"slots": 1
		},
		"Enforcer Class One": {
			"outfit": "/datum/outfit/job/inteq/celadon/enforcer",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/inteq/celadon/warden",
			"officer": true,
			"slots": 1
		},
		"Artificer Class One": {
			"outfit": "/datum/outfit/job/inteq/celadon/ce",
			"officer": true,
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/inteq/celadon/security",
			"slots": 4
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/inteq/celadon/engineer",
			"slots": 2
		},
		"Corspman": {
			"outfit": "/datum/outfit/job/inteq/celadon/paramedic",
			"slots": 1
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/inteq/assistant",
			"slots": 4
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/inteq_vaquero.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Vaquero-class Light Frigate",
	"map_short_name": "Vaquero",
	"description": "'Vaquero' - это гибкая и дешевая военная модификация малого коммерческого грузового судна, широко используемая InteQ Risk Management Group для патруля, разведки и сопровождения, а также для контрактов, которые не требуют более крупного и специализированного судна. В отличие от большинства суден InteQ, Vaquero оснащен базовым медицинским, инженерным и военным оборудованием, а его минимальные требования к экипажу отлично подходят для Vanguards с небольшим командованием и для учебных миссий. Как и любой другой корабль Интек, он оснащен большим грузовым отсеком, который может быть изменен по мере необходимости.",
	"map_path": "_maps/_mod_celadon/shuttles/inteq/inteq_vaquero.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 6,
	"prefix": "LIQSV",
	"faction": "/datum/faction/inteq",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"BEASTS",
		"INTEQ"
	],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/cel/inteq/captain",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/cel/inteq/warden",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/cel/inteq/engineer",
			"slots": 1
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/cel/inteq/paramedic",
			"slots": 1
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/cel/inteq/security",
			"slots": 1
		},
		"Auxiliary": {
			"outfit": "/datum/outfit/job/cel/inteq/assistant",
			"slots": 1
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/pirate_ember.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Ember-class Pirate Raider",
	"map_short_name": "Ember",
	"description": "Судно класса 'Ember' - это красный флаг в любом секторе. Гигантское, медленно движущееся, опасное в плане безопасности судно, самодельный почти во всех отношениях, пользуется благосклонностью самых безжалостных и жестоких пиратов и негодяев по всей галактике. Простое желание существовать на одном из этих суден - свидетельствует о выносливости, которая обычно не свойственна большинству жителей космоса. Лучший способ иметь дело с суднами 'Ember' - просто обходить их стороной. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Пираты - Имеет сильное вооружение, является Дредноутом пиратов по типу Твинклшайна или Херона. Для ивентов шип.",
	"map_path": "_maps/_mod_celadon/shuttles/pirate/pirate_ember.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 3,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/pirate/captain",
			"officer": true,
			"slots": 1
		},
		"Bridge Officer": {
			"outfit": "/datum/outfit/job/cel/pirate/hop",
			"officer": true,
			"slots": 2
		},
		"Shipswain": {
			"outfit": "/datum/outfit/job/cel/pirate/hos",
			"officer": true,
			"slots": 1
		},
		"Senior Sapper" :{
			"outfit": "/datum/outfit/job/cel/frontiersmen/ce",
			"officer": true,
			"slots": 1
		},
		"Cargo Tech": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/cargo_tech",
			"slots": 2
		},
		"Aidman": {
			"outfit": "/datum/outfit/job/cel/pirate/medic",
			"slots": 1
		},
		"Sapper": {
			"outfit": "/datum/outfit/job/cel/pirate/engineer",
			"slots": 2
		},
		"Atmospheric Technician": {
			"outfit": "/datum/outfit/job/cel/frontiersmen/atmos",
			"slots": 1
		},
		"Steward": {
			"outfit": "/datum/outfit/job/cel/pirate/cook",
			"slots": 1
		},
		"Boarder": {
			"outfit": "/datum/outfit/job/cel/pirate/security",
			"slots": 3
		},
		"Rookie": {
			"outfit": "/datum/outfit/job/cel/pirate/assistant",
			"slots": 3
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_schmiedeberg.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Schmiedeberg-class Pharmacology Ship",
	"map_short_name": "Schmiedeberg",
	"description": "Интересуетесь фармакологией, но устали сидеть перед химическим дозатором и целыми днями нажимать на кнопки? Хотите совместить кулинарное искусство с наркотическим? Надеетесь совместить все эти качества с самым важным занятием - зарабатыванием толстых пачек денег? Тогда судно класса 'Schmiedeberg' для вас! В 'Schmiedeberg' находится мощная химическая лаборатория, высокопроизводительная ботаническая установка и полноценная кухня-магазин, что делает его идеальным местом для химиков и ботаников, живущих в подворотнях.",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_schmiedeberg.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "IMV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Ботаника",
		"Медицинское"
	],
	"namelists": [
		"SUNS",
		"GENERAL"
	],
	"job_slots": {
		"Chief Pharmacist": {
			"outfit": "/datum/outfit/job/independent/cmo/pharma",
			"officer": true,
			"slots": 1
		},
		"Pharmacist": {
			"outfit": "/datum/outfit/job/independent/chemist/pharma",
			"slots": 1
		},
		"Mixologist": {
			"outfit": "/datum/outfit/job/independent/bartender/pharma",
			"slots": 1
		},
		"Herbalist": {
			"outfit": "/datum/outfit/job/independent/botanist/pharma",
			"slots": 2
		},
		"Pharmacology Student": {
			"outfit": "/datum/outfit/job/independent/assistant/pharma",
			"slots": 2
		}
	}
}

=== CeladonSS13/Shiptest/_maps/_mod_celadon/configs/independent_halftrack.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Halftrack-class Merchant Vessel",
	"map_short_name": "Halftrack",
	"description": "Редкое явление в Приграничье (но желанное), судно класса Halftrack - это сильно модернизированный вариант спасательного судна класса Li Tieguai, используемое в качестве передвижного магазина огнестрельного оружия предприимчивыми торговцами оружием повсюду. Если первоначальные варианты судна были скорее просто 'Li Tieguai', а медицинские приспособления были удалены и заменены оружейными стойками и шкафами для боеприпасов, то современная версия 'Halftrack' оснащена стрельбищем, сертифицированной службой безопасности InteQ и централизованным торговым залом, идеальным для демонстрации товаров и одновременного обеспечения их безопасности. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: ШИП НАХОДИТЬСЯ НА ДОРАБОТКЕ БАЛАНСА!",
	"map_path": "_maps/_mod_celadon/shuttles/independent/independent_halftrack.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
	"Торговый",
	"РП Фокус"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/independent/captain",
			"slots": 1
		},
		"IRMG Vanguard": {
			"outfit": "/datum/outfit/job/inteq/captain",
			"officer": true,
			"slots": 1
		},
		"IRMG Enforcer": {
			"outfit": "/datum/outfit/job/inteq/security",
			"slots": 2
		}
	}
}
